// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountUsers(ctx context.Context, search string) (int64, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetUser(ctx context.Context, argUuid uuid.UUID) (User, error)
	HardDeleteUser(ctx context.Context, argUuid uuid.UUID) (User, error)
	ListUsersOrderByIdASC(ctx context.Context, arg ListUsersOrderByIdASCParams) ([]User, error)
	ListUsersOrderByIdDESC(ctx context.Context, arg ListUsersOrderByIdDESCParams) ([]User, error)
	RestoreUser(ctx context.Context, argUuid uuid.UUID) (User, error)
	SoftDeleteUser(ctx context.Context, argUuid uuid.UUID) (User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
