// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users(email, password, fullname, age, status, role) VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, uuid, email, password, fullname, age, status, role, deleted_at, created_at, updated_at
`

type CreateUserParams struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Fullname string `json:"fullname"`
	Age      *int32 `json:"age"`
	Status   int32  `json:"status"`
	Role     int32  `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Password,
		arg.Fullname,
		arg.Age,
		arg.Status,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Email,
		&i.Password,
		&i.Fullname,
		&i.Age,
		&i.Status,
		&i.Role,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hardDeleteUser = `-- name: HardDeleteUser :one
DELETE FROM users
WHERE
  uuid = $1::uuid AND
  deleted_at IS NOT NULL
RETURNING id, uuid, email, password, fullname, age, status, role, deleted_at, created_at, updated_at
`

func (q *Queries) HardDeleteUser(ctx context.Context, argUuid uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, hardDeleteUser, argUuid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Email,
		&i.Password,
		&i.Fullname,
		&i.Age,
		&i.Status,
		&i.Role,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const restoreUser = `-- name: RestoreUser :one
UPDATE users
SET
  deleted_at = NULL
WHERE
  uuid = $1::uuid AND
  deleted_at IS NOT NULL
RETURNING id, uuid, email, password, fullname, age, status, role, deleted_at, created_at, updated_at
`

func (q *Queries) RestoreUser(ctx context.Context, argUuid uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, restoreUser, argUuid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Email,
		&i.Password,
		&i.Fullname,
		&i.Age,
		&i.Status,
		&i.Role,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeleteUser = `-- name: SoftDeleteUser :one
UPDATE users
SET
  deleted_at = NOW()
WHERE
  uuid = $1::uuid AND
  deleted_at IS NULL
RETURNING id, uuid, email, password, fullname, age, status, role, deleted_at, created_at, updated_at
`

func (q *Queries) SoftDeleteUser(ctx context.Context, argUuid uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, softDeleteUser, argUuid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Email,
		&i.Password,
		&i.Fullname,
		&i.Age,
		&i.Status,
		&i.Role,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
  password = COALESCE($1, password),
  fullname = COALESCE($2, fullname),
  age = COALESCE($3, age),
  status = COALESCE($4, status),
  role = COALESCE($5, role)
WHERE
  uuid = $6::uuid AND
  deleted_at IS NULL
RETURNING id, uuid, email, password, fullname, age, status, role, deleted_at, created_at, updated_at
`

type UpdateUserParams struct {
	Password *string   `json:"password"`
	Fullname *string   `json:"fullname"`
	Age      *int32    `json:"age"`
	Status   *int32    `json:"status"`
	Role     *int32    `json:"role"`
	Uuid     uuid.UUID `json:"uuid"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Password,
		arg.Fullname,
		arg.Age,
		arg.Status,
		arg.Role,
		arg.Uuid,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Email,
		&i.Password,
		&i.Fullname,
		&i.Age,
		&i.Status,
		&i.Role,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
