CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS users (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid uuid  NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  email      varchar(150) UNIQUE NOT NULL,
  password   varchar(90) NOT NULL,
  fullname   varchar(100) NOT NULL,
  age        INT CHECK (age >= 1 AND age <= 150),
  status     INT NOT NULL DEFAULT 1 CHECK (status IN (1, 2, 3)),
  role       INT NOT NULL DEFAULT 1 CHECK (role IN (1, 2, 3)),
  deleted_at TIMESTAMPTZ DEFAULT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON COLUMN users.status IS 'status: 1 - Active, 2 - Inactive, 3 - Banned';
COMMENT ON COLUMN users.role   IS 'role: 1 - Admin, 2 - Moderator, 3 - Member';

-- Create trigger
CREATE OR REPLACE FUNCTION update_user_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER users_set_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
WHEN (OLD IS DISTINCT FROM NEW)
EXECUTE FUNCTION update_user_updated_at();
